baseURL = "https://hjardonk.github.io/hjk-hugo-test/"
relativeURLs = false
canonifyURLs = true
languageCode = "en-us"
title = "Hildeberto Jard√≥n-Kojakhmetov"

[params]
  tagline = "Dynamical systems, singularity theory, network science"
  affiliation = "University of Groningen"
  email = "you@rug.nl"
  github = ""
  scholar = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
