baseURL = "https://hildejk.xyz/"
canonifyURLs = true
relativeURLs = false
languageCode = "en-us"
title = "Hildeberto Jard√≥n-Kojakhmetov"

[params]
  tagline = "Dynamical systems and network science"
  affiliation = "University of Groningen"
  email = "you@rug.nl"
  github = ""
  scholar = ""

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
